# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1193, 789)
        MainWindow.setStyleSheet("\n"
"      /*\n"
"      Ubuntu Style Sheet for QT Applications\n"
"          Author: Jaime A. Quiroga P.\n"
"          Company: GTRONICK\n"
"          Last updated: 01/10/2021 (dd/mm/yyyy), 15:18.\n"
"          Available at: https://github.com/GTRONICK/QSS/blob/master/Ubuntu.qss\n"
"          */\n"
"          QMainWindow {\n"
"            background-color:#f0f0f0;\n"
"          }\n"
"          QCheckBox {\n"
"            padding:2px;\n"
"          }\n"
"          QCheckBox:hover {\n"
"            border:1px solid rgb(255,150,60);\n"
"            border-radius:4px;\n"
"            padding: 1px;\n"
"            background-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(190, 90, 50, 50), stop:1 rgba(250, 130, 40, 50));\n"
"          }\n"
"          QCheckBox::indicator:checked {\n"
"            border:1px solid rgb(246, 134, 86);\n"
"            border-radius:4px;\n"
"              background-color:rgb(246, 134, 86)\n"
"          }\n"
"          QCheckBox::indicator:unchecked {\n"
"            border-width:1px solid rgb(246, 134, 86);\n"
"            border-radius:4px;\n"
"              background-color:rgb(255,255,255);\n"
"          }\n"
"          QColorDialog {\n"
"            background-color:#f0f0f0;\n"
"          }\n"
"          QComboBox {\n"
"            color:rgb(81,72,65);\n"
"            background: #ffffff;\n"
"          }\n"
"          QComboBox:editable {\n"
"            selection-color:rgb(81,72,65);\n"
"            selection-background-color: #ffffff;\n"
"          }\n"
"          QComboBox QAbstractItemView {\n"
"            selection-color: #ffffff;\n"
"            selection-background-color: rgb(246, 134, 86);\n"
"          }\n"
"          QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"            color:  #1e1d23;    \n"
"          }\n"
"          QDateTimeEdit, QDateEdit, QDoubleSpinBox, QFontComboBox {\n"
"            color:rgb(81,72,65);\n"
"            background-color: #ffffff;\n"
"          }\n"
"\n"
"          QDialog {\n"
"            background-color:#f0f0f0;\n"
"          }\n"
"\n"
"          QLabel,QLineEdit {\n"
"            color:rgb(17,17,17);\n"
"          }\n"
"          QLineEdit {\n"
"            background-color:rgb(255,255,255);\n"
"            selection-background-color:rgb(236,116,64);\n"
"          }\n"
"          QMenuBar {\n"
"            color:rgb(223,219,210);\n"
"            background-color:rgb(65,64,59);\n"
"          }\n"
"          QMenuBar::item {\n"
"            padding-top:4px;\n"
"            padding-left:4px;\n"
"            padding-right:4px;\n"
"            color:rgb(223,219,210);\n"
"            background-color:rgb(65,64,59);\n"
"          }\n"
"          QMenuBar::item:selected {\n"
"            color:rgb(255,255,255);\n"
"            padding-top:2px;\n"
"            padding-left:2px;\n"
"            padding-right:2px;\n"
"            border-top-width:2px;\n"
"            border-left-width:2px;\n"
"            border-right-width:2px;\n"
"            border-top-right-radius:4px;\n"
"            border-top-left-radius:4px;\n"
"            border-style:solid;\n"
"            background-color:rgb(65,64,59);\n"
"            border-top-color: rgb(47,47,44);\n"
"            border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"            border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"          }\n"
"          QMenu {\n"
"            color:rgb(223,219,210);\n"
"            background-color:rgb(65,64,59);\n"
"          }\n"
"          QMenu::item {\n"
"            color:rgb(223,219,210);\n"
"            padding:4px 10px 4px 20px;\n"
"          }\n"
"          QMenu::item:selected {\n"
"            color:rgb(255,255,255);\n"
"            background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"            border-style:solid;\n"
"            border-width:3px;\n"
"            padding:4px 7px 4px 17px;\n"
"            border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"            border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"            border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"            border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"          }\n"
"          QPlainTextEdit {\n"
"            border: 1px solid transparent;\n"
"            color:rgb(17,17,17);\n"
"            selection-background-color:rgb(236,116,64);\n"
"              background-color: #FFFFFF;\n"
"          }\n"
"          QProgressBar {\n"
"            text-align: center;\n"
"            color: rgb(0, 0, 0);\n"
"            border: 1px inset rgb(150,150,150); \n"
"            border-radius: 10px;\n"
"            background-color:rgb(221,221,219);\n"
"          }\n"
"          QProgressBar::chunk:horizontal {\n"
"            background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"            border:1px solid;\n"
"            border-radius:8px;\n"
"            border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"            border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"            border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"            border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"          }\n"
"          QPushButton{\n"
"            color:rgb(17,17,17);\n"
"            border-width: 1px;\n"
"            border-radius: 6px;\n"
"            border-bottom-color: rgb(150,150,150);\n"
"            border-right-color: rgb(165,165,165);\n"
"            border-left-color: rgb(165,165,165);\n"
"            border-top-color: rgb(180,180,180);\n"
"            border-style: solid;\n"
"            padding: 4px;\n"
"            background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"          }\n"
"          QPushButton:hover{\n"
"            color:rgb(17,17,17);\n"
"            border-width: 1px;\n"
"            border-radius:6px;\n"
"            border-top-color: rgb(255,150,60);\n"
"            border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"            border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"            border-bottom-color: rgb(200,70,20);\n"
"            border-style: solid;\n"
"            padding: 2px;\n"
"            background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"          }\n"
"          QPushButton:default{\n"
"            color:rgb(17,17,17);\n"
"            border-width: 1px;\n"
"            border-radius:6px;\n"
"            border-top-color: rgb(255,150,60);\n"
"            border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"            border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"            border-bottom-color: rgb(200,70,20);\n"
"            border-style: solid;\n"
"            padding: 2px;\n"
"            background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"          }\n"
"          QPushButton:pressed{\n"
"            color:rgb(17,17,17);\n"
"            border-width: 1px;\n"
"            border-radius: 6px;\n"
"            border-width: 1px;\n"
"            border-top-color: rgba(255,150,60,200);\n"
"            border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"            border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"            border-bottom-color: rgba(200,70,20,200);\n"
"            border-style: solid;\n"
"            padding: 2px;\n"
"            background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"          }\n"
"          QPushButton:disabled{\n"
"            color:rgb(174,167,159);\n"
"            border-width: 1px;\n"
"            border-radius: 6px;\n"
"            background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(230, 230, 230, 255));\n"
"          }\n"
"          QRadioButton {\n"
"            padding: 1px;\n"
"          }\n"
"          QRadioButton::indicator:checked {\n"
"            height: 10px;\n"
"            width: 10px;\n"
"            border-style:solid;\n"
"            border-radius:5px;\n"
"            border-width: 1px;\n"
"            border-color: rgba(246, 134, 86, 255);\n"
"            color: #a9b7c6;\n"
"            background-color:rgba(246, 134, 86, 255);\n"
"          }\n"
"          QRadioButton::indicator:!checked {\n"
"            height: 10px;\n"
"            width: 10px;\n"
"            border-style:solid;\n"
"            border-radius:5px;\n"
"            border-width: 1px;\n"
"            border-color: rgb(246, 134, 86);\n"
"            color: #a9b7c6;\n"
"            background-color: transparent;\n"
"          }\n"
"          QScrollArea {\n"
"            color: white;\n"
"            background-color:#f0f0f0;\n"
"          }\n"
"          QSlider::groove {\n"
"            border-style: solid;\n"
"            border-width: 1px;\n"
"            border-color: rgb(207,207,207);\n"
"          }\n"
"          QSlider::groove:horizontal {\n"
"            height: 5px;\n"
"            background: rgb(246, 134, 86);\n"
"          }\n"
"          QSlider::groove:vertical {\n"
"            width: 5px;\n"
"            background: rgb(246, 134, 86);\n"
"          }\n"
"          QSlider::handle:horizontal {\n"
"            background: rgb(253,253,253);\n"
"            border-style: solid;\n"
"            border-width: 1px;\n"
"            border-color: rgb(207,207,207);\n"
"            width: 12px;\n"
"            margin: -5px 0;\n"
"            border-radius: 7px;\n"
"          }\n"
"          QSlider::handle:vertical {\n"
"            background: rgb(253,253,253);\n"
"            border-style: solid;\n"
"            border-width: 1px;\n"
"            border-color: rgb(207,207,207);\n"
"            height: 12px;\n"
"            margin: 0 -5px;\n"
"            border-radius: 7px;\n"
"          }\n"
"          QSlider::add-page:horizontal, QSlider::add-page:vertical {\n"
"            background: white;\n"
"          }\n"
"          QSlider::sub-page:horizontal, QSlider::sub-page:vertical {\n"
"            background: rgb(246, 134, 86);\n"
"          }\n"
"          QStatusBar, QSpinBox {\n"
"            color:rgb(81,72,65);\n"
"          }\n"
"          QSpinBox {\n"
"            background-color: #ffffff;\n"
"          }\n"
"          QScrollBar:horizontal {\n"
"            max-height: 20px;\n"
"            border: 1px transparent;\n"
"            margin: 0px 20px 0px 20px;\n"
"          }\n"
"          QScrollBar::handle:horizontal {\n"
"            background: rgb(253,253,253);\n"
"            border: 1px solid rgb(207,207,207);\n"
"            border-radius: 7px;\n"
"            min-width: 25px;\n"
"          }\n"
"          QScrollBar::handle:horizontal:hover {\n"
"            background: rgb(253,253,253);\n"
"            border: 1px solid rgb(255,150,60);\n"
"            border-radius: 7px;\n"
"            min-width: 25px;\n"
"          }\n"
"          QScrollBar::add-line:horizontal {\n"
"              border: 1px solid rgb(207,207,207);\n"
"              border-top-right-radius: 7px;\n"
"              border-top-left-radius: 7px;\n"
"              border-bottom-right-radius: 7px;\n"
"              background: rgb(255, 255, 255);\n"
"              width: 20px;\n"
"              subcontrol-position: right;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::add-line:horizontal:hover {\n"
"              border: 1px solid rgb(255,150,60);\n"
"              border-top-right-radius: 7px;\n"
"              border-top-left-radius: 7px;\n"
"              border-bottom-right-radius: 7px;\n"
"              background: rgb(255, 255, 255);\n"
"              width: 20px;\n"
"              subcontrol-position: right;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::add-line:horizontal:pressed {\n"
"              border: 1px solid grey;\n"
"              border-top-left-radius: 7px;\n"
"              border-top-right-radius: 7px;\n"
"              border-bottom-right-radius: 7px;\n"
"              background: rgb(231,231,231);\n"
"              width: 20px;\n"
"              subcontrol-position: right;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::sub-line:horizontal {\n"
"              border: 1px solid rgb(207,207,207);\n"
"              border-top-right-radius: 7px;\n"
"              border-top-left-radius: 7px;\n"
"              border-bottom-left-radius: 7px;\n"
"              background: rgb(255, 255, 255);\n"
"              width: 20px;\n"
"              subcontrol-position: left;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::sub-line:horizontal:hover {\n"
"              border: 1px solid rgb(255,150,60);\n"
"              border-top-right-radius: 7px;\n"
"              border-top-left-radius: 7px;\n"
"              border-bottom-left-radius: 7px;\n"
"              background: rgb(255, 255, 255);\n"
"              width: 20px;\n"
"              subcontrol-position: left;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::sub-line:horizontal:pressed {\n"
"              border: 1px solid grey;\n"
"              border-top-right-radius: 7px;\n"
"              border-top-left-radius: 7px;\n"
"              border-bottom-left-radius: 7px;\n"
"              background: rgb(231,231,231);\n"
"              width: 20px;\n"
"              subcontrol-position: left;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::left-arrow:horizontal {\n"
"              border: 1px transparent grey;\n"
"              border-top-left-radius: 3px;\n"
"              border-bottom-left-radius: 3px;\n"
"              width: 6px;\n"
"              height: 6px;\n"
"              background: rgb(230,230,230);\n"
"          }\n"
"          QScrollBar::right-arrow:horizontal {\n"
"            border: 1px transparent grey;\n"
"            border-top-right-radius: 3px;\n"
"            border-bottom-right-radius: 3px;\n"
"              width: 6px;\n"
"              height: 6px;\n"
"            background: rgb(230,230,230);\n"
"          }\n"
"          QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"            background: none;\n"
"          } \n"
"          QScrollBar:vertical {\n"
"            max-width: 20px;\n"
"            border: 1px transparent grey;\n"
"            margin: 20px 0px 20px 0px;\n"
"          }\n"
"          QScrollBar::add-line:vertical {\n"
"            border: 1px solid;\n"
"            border-color: rgb(207,207,207);\n"
"            border-bottom-right-radius: 7px;\n"
"            border-bottom-left-radius: 7px;\n"
"            border-top-left-radius: 7px;\n"
"            background: rgb(255, 255, 255);\n"
"              height: 20px;\n"
"              subcontrol-position: bottom;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::add-line:vertical:hover {\n"
"              border: 1px solid;\n"
"              border-color: rgb(255,150,60);\n"
"              border-bottom-right-radius: 7px;\n"
"              border-bottom-left-radius: 7px;\n"
"              border-top-left-radius: 7px;\n"
"              background: rgb(255, 255, 255);\n"
"              height: 20px;\n"
"              subcontrol-position: bottom;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::add-line:vertical:pressed {\n"
"              border: 1px solid grey;\n"
"              border-bottom-left-radius: 7px;\n"
"              border-bottom-right-radius: 7px;\n"
"              border-top-left-radius: 7px;\n"
"              background: rgb(231,231,231);\n"
"              height: 20px;\n"
"              subcontrol-position: bottom;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::sub-line:vertical {\n"
"              border: 1px solid rgb(207,207,207);\n"
"              border-top-right-radius: 7px;\n"
"              border-top-left-radius: 7px;\n"
"              border-bottom-left-radius: 7px;\n"
"              background: rgb(255, 255, 255);\n"
"              height: 20px;\n"
"              subcontrol-position: top;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::sub-line:vertical:hover {\n"
"              border: 1px solid rgb(255,150,60);\n"
"              border-top-right-radius: 7px;\n"
"              border-top-left-radius: 7px;\n"
"              border-bottom-left-radius: 7px;\n"
"            background: rgb(255, 255, 255);\n"
"              height: 20px;\n"
"              subcontrol-position: top;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::sub-line:vertical:pressed {\n"
"              border: 1px solid grey;\n"
"              border-top-left-radius: 7px;\n"
"              border-top-right-radius: 7px;\n"
"              background: rgb(231,231,231);\n"
"            height: 20px;\n"
"              subcontrol-position: top;\n"
"              subcontrol-origin: margin;\n"
"          }\n"
"          QScrollBar::handle:vertical {\n"
"            background: rgb(253,253,253);\n"
"            border: 1px solid rgb(207,207,207);\n"
"            border-radius: 7px;\n"
"            min-height: 25px;\n"
"          }\n"
"          QScrollBar::handle:vertical:hover {\n"
"            background: rgb(253,253,253);\n"
"            border: 1px solid rgb(255,150,60);\n"
"            border-radius: 7px;\n"
"            min-height: 25px;\n"
"          }\n"
"          QScrollBar::up-arrow:vertical {\n"
"            border: 1px transparent grey;\n"
"              border-top-left-radius: 3px;\n"
"            border-top-right-radius: 3px;\n"
"              width: 6px;\n"
"              height: 6px;\n"
"              background: rgb(230,230,230);\n"
"          }\n"
"          QScrollBar::down-arrow:vertical {\n"
"              border: 1px transparent grey;\n"
"              border-bottom-left-radius: 3px;\n"
"              border-bottom-right-radius: 3px;\n"
"              width: 6px;\n"
"              height: 6px;\n"
"              background: rgb(230,230,230);\n"
"          }\n"
"          QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"              background: none;\n"
"          }\n"
"          QTabWidget {\n"
"            color:rgb(0,0,0);\n"
"            background-color:rgb(247,246,246);\n"
"          }\n"
"          QTabWidget::pane {\n"
"            border-color: rgb(180,180,180);\n"
"            background-color:rgb(247,246,246);\n"
"            border-style: solid;\n"
"            border-width: 1px;\n"
"              border-radius: 6px;\n"
"          }\n"
"          QTabBar::tab {\n"
"            padding-left:4px;\n"
"            padding-right:4px;\n"
"            padding-bottom:2px;\n"
"            padding-top:2px;\n"
"            color:rgb(81,72,65);\n"
"              background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(221,218,217,255), stop:1 rgba(240,239,238,255));\n"
"            border-style: solid;\n"
"            border-width: 1px;\n"
"              border-top-right-radius:4px;\n"
"            border-top-left-radius:4px;\n"
"            border-top-color: rgb(180,180,180);\n"
"            border-left-color: rgb(180,180,180);\n"
"            border-right-color: rgb(180,180,180);\n"
"            border-bottom-color: transparent;\n"
"          }\n"
"          QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"              background-color:rgb(247,246,246);\n"
"              margin-left: 0px;\n"
"              margin-right: 1px;\n"
"          }\n"
"          QTabBar::tab:!selected {\n"
"            margin-top: 1px;\n"
"            margin-right: 1px;\n"
"          }\n"
"          QTextEdit {\n"
"            border-width: 1px;\n"
"            border-style: solid;\n"
"            border-color:transparent;\n"
"            color:rgb(17,17,17);\n"
"            selection-background-color:rgb(236,116,64);\n"
"          }\n"
"          QTimeEdit, QToolBox, QToolBox::tab, QToolBox::tab:selected {\n"
"            color:rgb(81,72,65);\n"
"            background-color: #ffffff;\n"
"          }\n"
"    ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 7, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wgt_inputs = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_inputs.sizePolicy().hasHeightForWidth())
        self.wgt_inputs.setSizePolicy(sizePolicy)
        self.wgt_inputs.setObjectName("wgt_inputs")
        self.gridLayout = QtWidgets.QGridLayout(self.wgt_inputs)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.viewport1 = Viewport(self.wgt_inputs)
        self.viewport1.setStyleSheet("border-color: black")
        self.viewport1.setObjectName("viewport1")
        self.gridLayout.addWidget(self.viewport1, 0, 0, 1, 1)
        self.viewport2 = Viewport(self.wgt_inputs)
        self.viewport2.setStyleSheet("border-color: black")
        self.viewport2.setObjectName("viewport2")
        self.gridLayout.addWidget(self.viewport2, 0, 1, 1, 1)
        self.viewport3 = Viewport(self.wgt_inputs)
        self.viewport3.setStyleSheet("border-color: black")
        self.viewport3.setObjectName("viewport3")
        self.gridLayout.addWidget(self.viewport3, 0, 2, 1, 1)
        self.viewport4 = Viewport(self.wgt_inputs)
        self.viewport4.setStyleSheet("border-color: black")
        self.viewport4.setObjectName("viewport4")
        self.gridLayout.addWidget(self.viewport4, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.wgt_inputs, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 1, 1)
        self.wgt_outputs = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_outputs.sizePolicy().hasHeightForWidth())
        self.wgt_outputs.setSizePolicy(sizePolicy)
        self.wgt_outputs.setMinimumSize(QtCore.QSize(400, 0))
        self.wgt_outputs.setMaximumSize(QtCore.QSize(700, 16777215))
        self.wgt_outputs.setSizeIncrement(QtCore.QSize(0, 0))
        self.wgt_outputs.setBaseSize(QtCore.QSize(700, 0))
        self.wgt_outputs.setObjectName("wgt_outputs")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wgt_outputs)
        self.verticalLayout.setContentsMargins(0, 0, 7, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.viewport5 = Viewport(self.wgt_outputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewport5.sizePolicy().hasHeightForWidth())
        self.viewport5.setSizePolicy(sizePolicy)
        self.viewport5.setStyleSheet("border-color: black")
        self.viewport5.setProperty("can_browse", False)
        self.viewport5.setProperty("ft_enabled", False)
        self.viewport5.setObjectName("viewport5")
        self.verticalLayout.addWidget(self.viewport5)
        self.viewport6 = Viewport(self.wgt_outputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewport6.sizePolicy().hasHeightForWidth())
        self.viewport6.setSizePolicy(sizePolicy)
        self.viewport6.setStyleSheet("QLabel {\n"
"            background: white;\n"
"}")
        self.viewport6.setProperty("can_browse", False)
        self.viewport6.setProperty("ft_enabled", False)
        self.viewport6.setObjectName("viewport6")
        self.verticalLayout.addWidget(self.viewport6)
        self.gridLayout_2.addWidget(self.wgt_outputs, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1193, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(879, 88))
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget = QtWidgets.QWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radio_out_1 = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_out_1.sizePolicy().hasHeightForWidth())
        self.radio_out_1.setSizePolicy(sizePolicy)
        self.radio_out_1.setChecked(True)
        self.radio_out_1.setObjectName("radio_out_1")
        self.output_radio_button_group = QtWidgets.QButtonGroup(MainWindow)
        self.output_radio_button_group.setObjectName("output_radio_button_group")
        self.output_radio_button_group.addButton(self.radio_out_1)
        self.horizontalLayout_5.addWidget(self.radio_out_1)
        self.radio_out_2 = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_out_2.sizePolicy().hasHeightForWidth())
        self.radio_out_2.setSizePolicy(sizePolicy)
        self.radio_out_2.setObjectName("radio_out_2")
        self.output_radio_button_group.addButton(self.radio_out_2)
        self.horizontalLayout_5.addWidget(self.radio_out_2)
        self.horizontalLayout_6.addWidget(self.widget)
        self.chkbx_invert = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.chkbx_invert.setObjectName("chkbx_invert")
        self.horizontalLayout_6.addWidget(self.chkbx_invert)
        self.btn_mix = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mix.sizePolicy().hasHeightForWidth())
        self.btn_mix.setSizePolicy(sizePolicy)
        self.btn_mix.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_mix.setObjectName("btn_mix")
        self.horizontalLayout_6.addWidget(self.btn_mix)
        self.cmbx_mix = QtWidgets.QComboBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbx_mix.sizePolicy().hasHeightForWidth())
        self.cmbx_mix.setSizePolicy(sizePolicy)
        self.cmbx_mix.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cmbx_mix.setObjectName("cmbx_mix")
        self.cmbx_mix.addItem("")
        self.cmbx_mix.addItem("")
        self.horizontalLayout_6.addWidget(self.cmbx_mix)
        self.wgt_mix_1 = QtWidgets.QWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_mix_1.sizePolicy().hasHeightForWidth())
        self.wgt_mix_1.setSizePolicy(sizePolicy)
        self.wgt_mix_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.wgt_mix_1.setObjectName("wgt_mix_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wgt_mix_1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_image1 = QtWidgets.QLabel(self.wgt_mix_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_image1.sizePolicy().hasHeightForWidth())
        self.lbl_image1.setSizePolicy(sizePolicy)
        self.lbl_image1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_image1.setObjectName("lbl_image1")
        self.horizontalLayout.addWidget(self.lbl_image1)
        self.slider_mix_1 = QtWidgets.QSlider(self.wgt_mix_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_mix_1.sizePolicy().hasHeightForWidth())
        self.slider_mix_1.setSizePolicy(sizePolicy)
        self.slider_mix_1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.slider_mix_1.setMaximum(20)
        self.slider_mix_1.setProperty("value", 10)
        self.slider_mix_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_mix_1.setObjectName("slider_mix_1")
        self.horizontalLayout.addWidget(self.slider_mix_1)
        self.horizontalLayout_6.addWidget(self.wgt_mix_1)
        self.wgt_mix_2 = QtWidgets.QWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_mix_2.sizePolicy().hasHeightForWidth())
        self.wgt_mix_2.setSizePolicy(sizePolicy)
        self.wgt_mix_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.wgt_mix_2.setObjectName("wgt_mix_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wgt_mix_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_image2 = QtWidgets.QLabel(self.wgt_mix_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_image2.sizePolicy().hasHeightForWidth())
        self.lbl_image2.setSizePolicy(sizePolicy)
        self.lbl_image2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_image2.setObjectName("lbl_image2")
        self.horizontalLayout_2.addWidget(self.lbl_image2)
        self.slider_mix_2 = QtWidgets.QSlider(self.wgt_mix_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_mix_2.sizePolicy().hasHeightForWidth())
        self.slider_mix_2.setSizePolicy(sizePolicy)
        self.slider_mix_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.slider_mix_2.setMaximum(20)
        self.slider_mix_2.setProperty("value", 10)
        self.slider_mix_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_mix_2.setObjectName("slider_mix_2")
        self.horizontalLayout_2.addWidget(self.slider_mix_2)
        self.horizontalLayout_6.addWidget(self.wgt_mix_2)
        self.wgt_mix_3 = QtWidgets.QWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_mix_3.sizePolicy().hasHeightForWidth())
        self.wgt_mix_3.setSizePolicy(sizePolicy)
        self.wgt_mix_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.wgt_mix_3.setObjectName("wgt_mix_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wgt_mix_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_image3 = QtWidgets.QLabel(self.wgt_mix_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_image3.sizePolicy().hasHeightForWidth())
        self.lbl_image3.setSizePolicy(sizePolicy)
        self.lbl_image3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_image3.setObjectName("lbl_image3")
        self.horizontalLayout_3.addWidget(self.lbl_image3)
        self.slider_mix_3 = QtWidgets.QSlider(self.wgt_mix_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_mix_3.sizePolicy().hasHeightForWidth())
        self.slider_mix_3.setSizePolicy(sizePolicy)
        self.slider_mix_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.slider_mix_3.setMaximum(20)
        self.slider_mix_3.setProperty("value", 10)
        self.slider_mix_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_mix_3.setObjectName("slider_mix_3")
        self.horizontalLayout_3.addWidget(self.slider_mix_3)
        self.horizontalLayout_6.addWidget(self.wgt_mix_3)
        self.wgt_mix_4 = QtWidgets.QWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_mix_4.sizePolicy().hasHeightForWidth())
        self.wgt_mix_4.setSizePolicy(sizePolicy)
        self.wgt_mix_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.wgt_mix_4.setObjectName("wgt_mix_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wgt_mix_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_image4 = QtWidgets.QLabel(self.wgt_mix_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_image4.sizePolicy().hasHeightForWidth())
        self.lbl_image4.setSizePolicy(sizePolicy)
        self.lbl_image4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_image4.setObjectName("lbl_image4")
        self.horizontalLayout_4.addWidget(self.lbl_image4)
        self.slider_mix_4 = QtWidgets.QSlider(self.wgt_mix_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_mix_4.sizePolicy().hasHeightForWidth())
        self.slider_mix_4.setSizePolicy(sizePolicy)
        self.slider_mix_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.slider_mix_4.setMaximum(20)
        self.slider_mix_4.setProperty("value", 10)
        self.slider_mix_4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_mix_4.setObjectName("slider_mix_4")
        self.horizontalLayout_4.addWidget(self.slider_mix_4)
        self.horizontalLayout_6.addWidget(self.wgt_mix_4)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Mix"))
        self.radio_out_1.setText(_translate("MainWindow", "Output 1"))
        self.radio_out_2.setText(_translate("MainWindow", "Output 2"))
        self.chkbx_invert.setText(_translate("MainWindow", "Invert Selection"))
        self.btn_mix.setText(_translate("MainWindow", "Mix!"))
        self.cmbx_mix.setItemText(0, _translate("MainWindow", "FT Magnitude"))
        self.cmbx_mix.setItemText(1, _translate("MainWindow", "FT Real"))
        self.lbl_image1.setText(_translate("MainWindow", "Image 1"))
        self.lbl_image2.setText(_translate("MainWindow", "Image 2"))
        self.lbl_image3.setText(_translate("MainWindow", "Image 3"))
        self.lbl_image4.setText(_translate("MainWindow", "Image 4"))
        self.actionOpen.setText(_translate("MainWindow", "Open (Temporary)"))
from viewport import Viewport


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
